// const apple = " hello @ ok"
// console.log(apple);
// console.log(apple[1])
// console.log(apple.toUpperCase())
// console.log(apple.includes('@'));
// console.log(apple.includes('f'));
// console.log(apple.trim());
// console.log(apple[1]);
// console.log(apple.split(" "))//it changes to array
// console.log(apple.slice(4,7));
//  console.log(apple)

//  //number 
//  priority :
//  (),
//  **--(power)
//  *,/,% left to right
//  +,-

const a = 3*7 + 4**(3+1) % 10/5;
console.log(a);